#pragma once
#include "Editor/Panels/IEditorPanel.hpp"
#include "Editor/Panels/ViewportPanel.hpp"
#include "Editor/Panels/SceneHierarchyPanel.hpp"
#include "Editor/Panels/InspectorPanel.hpp"
#include "Editor/Panels/ContentBrowserPanel.hpp"
#include "Editor/Panels/TerminalPanel.hpp"
#include "Editor/Panels/SettingsPanels.hpp"
#include "Editor/Panels/PluginsPanel.hpp"
