name: Windows Build (Clang)

on:
  pull_request:
    branches: [ main, ecs, editor, gameplay, ui, samples ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-clang:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Logger Dependency
        shell: cmd
        run: |
          cd Vendor\Customizable_Logger
          if not exist build mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -T ClangCL -A x64
          cmake --build . --config Debug -- /m:1

      - name: Build GLFW Dependency
        shell: cmd
        run: |
          cd Vendor\GLFW
          if not exist build mkdir build
          cd build
          cmake ../glfw -G "Visual Studio 17 2022" -T ClangCL -A x64 -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_EXAMPLES=OFF
          cmake --build . --config Debug -- /m:1

      - name: Generate Solution with Premake
        shell: cmd
        run: Vendor\Premake\premake5.exe vs2022

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution (ClangCL)
        shell: cmd
        run: msbuild TimeEngine.sln /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=ClangCL /m
